In [5]:
import pandas as pd

In [6]:
df=pd.read_csv("C:\\Users\\Admin\\OneDrive\\Desktop\\Real Estate Mapping\\data\\Zillow properties.csv")

In [7]:
df

,zpid,city,state,homeStatus,address,isListingClaimedByCurrentSignedInUser,isCurrentSignedInAgentResponsible,bedrooms,bathrooms,price,...,interior_full,property,construction,tag,contingent_listing_type,unit_number,unit_amenities,open_house_details,community_details,mls_id
0,15121959,San Francisco,CA,SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,3,2,1480000,...,"[{""title"":""MasterBedroom"",""values"":[""Area: 0""]...","[{""title"":""Parking"",""values"":[""Total spaces: 2...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,NaN,423717855
1,15077058,San Francisco,CA,SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,1,1,890000,...,"[{""title"":""MasterBedroom"",""values"":[""Features:...","[{""title"":""Parking"",""values"":[""Total spaces: 1...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,NaN,421579203
2,15158041,San Francisco,CA,RECENTLY_SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,2,1,1000000,...,"[{""title"":""MasterBedroom"",""values"":[""Features:...","[{""title"":""Parking"",""values"":[""Total spaces: 3...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,"[{""title"":""Security"",""values"":[""Carbon Monoxid...",423900225
3,15104519,San Francisco,CA,RECENTLY_SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,2,1,1615000,...,"[{""title"":""Bathroom"",""values"":[""Features: Show...","[{""title"":""Parking"",""values"":[""Total spaces: 1...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,NaN,ML81960052
4,15113307,San Francisco,CA,SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,3,2,1600000,...,"[{""title"":""MasterBedroom"",""values"":[""Area: 0""]...","[{""title"":""Parking"",""values"":[""Total spaces: 2...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,"[{""title"":""Security"",""values"":[""Carbon Monoxid...",423759270
5,15108284,San Francisco,CA,RECENTLY_SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,2,1,1565000,...,"[{""title"":""Bathroom"",""values"":[""Features: Show...","[{""title"":""Parking"",""values"":[""Total spaces: 1...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,NaN,ML81946541
6,337888164,San Francisco,CA,SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,3,1,1100000,...,"[{""title"":""Bedrooms & bathrooms"",""values"":[""Be...","[{""title"":""Parking"",""values"":[""Total spaces: 3...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,NaN,41000623
7,332858282,San Francisco,CA,RECENTLY_SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,3,2,2650000,...,"[{""title"":""MasterBedroom"",""values"":[""Area: 0""]...","[{""title"":""Parking"",""values"":[""Total spaces: 2...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,NaN,424013555
8,15130114,San Francisco,CA,SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,2,3,1025000,...,"[{""title"":""MasterBedroom"",""values"":[""Area: 0""]...","[{""title"":""Parking"",""values"":[""Total spaces: 2...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,"[{""title"":""Features"",""values"":[""Gated""]}]",423757830
9,15076848,San Francisco,CA,SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,3,2,1130000,...,"[{""title"":""MasterBedroom"",""values"":[""Features:...","[{""title"":""Parking"",""values"":[""Total spaces: 1...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,"[{""title"":""Security"",""values"":[""Carbon Monoxid...",421611645
10,15088848,San Francisco,CA,SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,3,4,4525000,...,"[{""title"":""MasterBedroom"",""values"":[""Features:...","[{""title"":""Parking"",""values"":[""Total spaces: 2...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,NaN,423734752
11,15180687,San Francisco,CA,RECENTLY_SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,2,1,830000,...,"[{""title"":""MasterBedroom"",""values"":[""Area: 0""]...","[{""title"":""Parking"",""values"":[""Total spaces: 1...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,NaN,423925157
12,80735167,San Francisco,CA,SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,1,1,1005000,...,"[{""title"":""MasterBedroom"",""values"":[""Area: 0""]...","[{""title"":""Parking"",""values"":[""Total spaces: 1...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,NaN,422673020
13,15063579,San Francisco,CA,SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,1,1,740000,...,"[{""title"":""DiningRoom"",""values"":[""Features: Di...","[{""title"":""Parking"",""values"":[""Total spaces: 2...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,NaN,ML81867778
14,332854022,San Francisco,CA,RECENTLY_SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,3,0,1625000,...,"[{""title"":""Bedrooms & bathrooms"",""values"":[""Be...","[{""title"":""Features"",""values"":[""Patio & porch:...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,"[{""title"":""Security"",""values"":[""Carbon Monoxid...",423907780
15,332859868,San Francisco,CA,SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,2,1,1020000,...,"[{""title"":""MasterBedroom"",""values"":[""Area: 0""]...","[{""title"":""Parking"",""values"":[""Total spaces: 1...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,"[{""title"":""Security"",""values"":[""Security Fence...",422700275
16,335653827,San Francisco,CA,RECENTLY_SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,1,1,910000,...,"[{""title"":""MasterBedroom"",""values"":[""Area: 0""]...","[{""title"":""Parking"",""values"":[""Total spaces: 1...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,"[{""title"":""Security"",""values"":[""Carbon Monoxid...",424001058
17,335654154,San Francisco,CA,RECENTLY_SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,2,1,1099000,...,"[{""title"":""MasterBedroom"",""values"":[""Features:...","[{""title"":""Parking"",""values"":[""Total spaces: 1...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,"[{""title"":""Security"",""values"":[""Security Gate""]}]",422649975
18,15142488,San Francisco,CA,SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,2,2,715000,...,"[{""title"":""MasterBedroom"",""values"":[""Area: 0""]...","[{""title"":""Parking"",""values"":[""Total spaces: 1...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,"[{""title"":""Security"",""values"":[""Security Gate""]}]",422684947
19,15121634,San Francisco,CA,RECENTLY_SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,3,2,1325000,...,"[{""title"":""MasterBedroom"",""values"":[""Area: 0""]...","[{""title"":""Parking"",""values"":[""Total spaces: 1...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,NaN,424022251
20,335654108,San Francisco,CA,RECENTLY_SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,2,2,1220500,...,"[{""title"":""MasterBedroom"",""values"":[""Area: 0""]...","[{""title"":""Parking"",""values"":[""Total spaces: 1...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,NaN,424013862
21,15078175,San Francisco,CA,SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,1,1,461777,...,"[{""title"":""MasterBedroom"",""values"":[""Area: 0""]...","[{""title"":""Parking"",""values"":[""Total spaces: 1...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,"[{""title"":""Security"",""values"":[""Fire Alarm"",""S...",422657028
22,15109255,San Francisco,CA,RECENTLY_SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,3,2,1710000,...,"[{""title"":""MasterBedroom"",""values"":[""Area: 0""]...","[{""title"":""Parking"",""values"":[""Total spaces: 2...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,NaN,424015077
23,15198606,San Francisco,CA,SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,3,3,1760000,...,"[{""title"":""MasterBedroom"",""values"":[""Features:...","[{""title"":""Parking"",""values"":[""Total spaces: 2...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,"[{""title"":""Security"",""values"":[""Carbon Monoxid...",422635265
24,53153616,San Francisco,CA,SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,1,1,950000,...,"[{""title"":""MasterBedroom"",""values"":[""Area: 0""]...","[{""title"":""Features"",""values"":[""Exterior featu...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,"[{""title"":""Security"",""values"":[""Carbon Monoxid...",423748380
25,15158469,San Francisco,CA,SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,2,1,1200000,...,"[{""title"":""DiningRoom"",""values"":[""Features: Ea...","[{""title"":""Parking"",""values"":[""Total spaces: 2...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,NaN,ML81883705
26,15190394,San Francisco,CA,RECENTLY_SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,2,1,940000,...,"[{""title"":""Bedrooms & bathrooms"",""values"":[""Be...","[{""title"":""Parking"",""values"":[""Total spaces: 2...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,"[{""title"":""Security"",""values"":[""Security Gate""]}]",41042965
27,125217698,San Francisco,CA,RECENTLY_SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,3,2,1325000,...,"[{""title"":""MasterBedroom"",""values"":[""Area: 0""]...","[{""title"":""Parking"",""values"":[""Total spaces: 1...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,NaN,424014816
28,89240334,San Francisco,CA,SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,3,3,1100000,...,"[{""title"":""MasterBedroom"",""values"":[""Features:...","[{""title"":""Features"",""values"":[""Levels: One"",""...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,"[{""title"":""Security"",""values"":[""Carbon Monoxid...",422667958
29,15092824,San Francisco,CA,RECENTLY_SOLD,"{""city"":""San Francisco"",""state"":""CA"",""streetAd...",False,False,3,2,1500000,...,"[{""title"":""MasterBedroom"",""values"":[""Features:...","[{""title"":""Parking"",""values"":[""Total spaces: 1...","[{""title"":""Type & style"",""values"":[""Home type:...",Sold,NaN,NaN,NaN,NaN,"[{""title"":""Security"",""values"":[""Carbon Monoxid...",424002493

In [8]:
list(df.columns)

['zpid',
 'city',
 'state',
 'homeStatus',
 'address',
 'isListingClaimedByCurrentSignedInUser',
 'isCurrentSignedInAgentResponsible',
 'bedrooms',
 'bathrooms',
 'price',
 'yearBuilt',
 'streetAddress',
 'zipcode',
 'isCurrentSignedInUserVerifiedOwner',
 'isVerifiedClaimedByCurrentSignedInUser',
 'listingDataSource',
 'longitude',
 'latitude',
 'hasBadGeocode',
 'streetViewMetadataUrlMediaWallLatLong',
 'streetViewMetadataUrlMediaWallAddress',
 'streetViewServiceUrl',
 'livingArea',
 'homeType',
 'lotSize',
 'lotAreaValue',
 'lotAreaUnits',
 'livingAreaValue',
 'livingAreaUnitsShort',
 'isUndisclosedAddress',
 'zestimate',
 'rentZestimate',
 'currency',
 'hideZestimate',
 'dateSoldString',
 'taxAssessedValue',
 'taxAssessedYear',
 'country',
 'propertyTaxRate',
 'photoCount',
 'isPremierBuilder',
 'isZillowOwned',
 'ssid',
 'hdpUrl',
 'tourViewCount',
 'hasPublicVideo',
 'lastSoldPrice',
 'livingAreaUnits',
 'hasApprovedThirdPartyVirtualTourUrl',
 'streetViewTileImageUrlMediumLatLong',
 'isNonOwnerOccupied',
 'zestimateMinus30',
 'restimateMinus30',
 'zestimateLowPercent',
 'zestimateHighPercent',
 'restimateLowPercent',
 'restimateHighPercent',
 'description',
 'parcelId',
 'taxHistory',
 'priceHistory',
 'nearbyHomes',
 'schools',
 'totalCount',
 'mortgageRates',
 'isInstantOfferEnabled',
 'zillowOfferMarket',
 'isRentalListingOffMarket',
 'nearbyCities',
 'nearbyNeighborhoods',
 'nearbyZipcodes',
 'abbreviatedAddress',
 'daysOnZillow',
 'rentalApplicationsAcceptedType',
 'brokerageName',
 'propertyTypeDimension',
 'hdpTypeDimension',
 'timeZone',
 'tourEligibility',
 'virtualTourUrl',
 'selfTour',
 'photos',
 'resoFacts:sewer',
 'resoFacts:waterSource',
 'utilities',
 'url',
 'countyFIPS',
 'countyID',
 'dateSold',
 'isFeatured',
 'isHousingConnector',
 'isRentalsLeadCapMet',
 'listingTypeDimension',
 'postingContact',
 'homeValuation',
 'isOffMarket',
 'resofacts_sewer',
 'resofacts_water_source',
 'citySearchUrl',
 'county',
 'is_showcased',
 'interior',
 'overview',
 'is_listed_by_management_company',
 'management_company_phone_number',
 'listing_provided_by',
 'hoa_details',
 'financial',
 'interior_full',
 'property',
 'construction',
 'tag',
 'contingent_listing_type',
 'unit_number',
 'unit_amenities',
 'open_house_details',
 'community_details',
 'mls_id']

In [9]:
df.describe()

,zpid,bedrooms,bathrooms,price,yearBuilt,zipcode,longitude,latitude,livingArea,lotSize,...,resoFacts:sewer,resoFacts:waterSource,utilities,countyFIPS,countyID,management_company_phone_number,contingent_listing_type,unit_number,unit_amenities,open_house_details
count,3.000000e+01,30.000000,30.000000,3.000000e+01,28.000000,30.000000,30.000000,30.000000,30.000000,29.000000,...,0.0,0.0,0.0,30.0,30.0,0.0,0.0,0.0,0.0,0.0
mean,9.930281e+07,2.233333,1.600000,1.333876e+06,1955.500000,94117.633333,-122.446685,37.762060,1307.200000,14313.793103,...,NaN,NaN,NaN,6075.0,3227.0,NaN,NaN,NaN,NaN,NaN
std,1.346825e+08,0.773854,0.855006,7.347398e+05,31.332742,8.197911,0.037972,0.021451,694.158106,27222.674510,...,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN
min,1.506358e+07,1.000000,0.000000,4.617770e+05,1890.000000,94103.000000,-122.508620,37.719547,0.000000,0.000000,...,NaN,NaN,NaN,6075.0,3227.0,NaN,NaN,NaN,NaN,NaN
25%,1.510853e+07,2.000000,1.000000,9.625000e+05,1941.000000,94110.000000,-122.487150,37.750811,910.500000,2334.000000,...,NaN,NaN,NaN,6075.0,3227.0,NaN,NaN,NaN,NaN,NaN
50%,1.515826e+07,2.000000,1.000000,1.115000e+06,1944.500000,94117.000000,-122.437872,37.758913,1100.500000,2996.000000,...,NaN,NaN,NaN,6075.0,3227.0,NaN,NaN,NaN,NaN,NaN
75%,1.162234e+08,3.000000,2.000000,1.548750e+06,1977.500000,94122.000000,-122.418720,37.779062,1530.750000,4884.000000,...,NaN,NaN,NaN,6075.0,3227.0,NaN,NaN,NaN,NaN,NaN
max,3.378882e+08,3.000000,4.000000,4.525000e+06,2020.000000,94133.000000,-122.390170,37.804690,3600.000000,123888.000000,...,NaN,NaN,NaN,6075.0,3227.0,NaN,NaN,NaN,NaN,NaN

In [10]:
df.isnull()

,zpid,city,state,homeStatus,address,isListingClaimedByCurrentSignedInUser,isCurrentSignedInAgentResponsible,bedrooms,bathrooms,price,...,interior_full,property,construction,tag,contingent_listing_type,unit_number,unit_amenities,open_house_details,community_details,mls_id
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,False,False
17,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,False
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,True,False
28,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,True,True,True,False,False

In [12]:
df.dtypes

zpid                    int64
city                   object
state                  object
homeStatus             object
address                object
                       ...
unit_number           float64
unit_amenities        float64
open_house_details    float64
community_details      object
mls_id                 object
Length: 118, dtype: object